- src/webapp/src/accounts/services/userCredentials.service.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/app.module.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/auth/local.strategy.ts
> Lgtm alerts

- src/webapp/package.json
- src/webapp/src/accounts/accounts.module.ts
- src/webapp/src/accounts/entities/user.entity.spec.ts
- src/webapp/src/accounts/entities/user.entity.ts
- src/webapp/src/accounts/services/accounts.service.spec.ts
- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/accounts/services/accountsUsers.service.spec.ts
- src/webapp/src/accounts/services/users.service.spec.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/api/controllers/v1/api.authentication.controller.ts
- src/webapp/src/app.module.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/notifications/notifications.module.ts
- src/webapp/src/notifications/notifications.service.ts
- src/webapp/src/settings/settings.module.ts
- src/webapp/src/settings/settings.service.spec.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/utilities/random.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/src/website/website.module.ts
- src/webapp/test/authentication.e2e-spec.ts
- src/webapp/themes/bare/email/confirm_email.liquid
- src/webapp/themes/bare/email/new_account.liquid
- src/webapp/themes/bare/email/reset_email.liquid
- src/webapp/yarn.lock
Add email notification feature
Add email confirmation
_Solved_
#18
#20 
_Added_
None.
None, but JTW reissuing still to be tested.
> Notification module

- src/webapp/src/auth/auth.guard.ts
- src/webapp/src/filters/http-exceptions.filter.spec.ts
- src/webapp/src/filters/http-exceptions.filter.ts
- src/webapp/src/main.app.ts
- src/webapp/src/payments/services/payments.service.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/themes/bare/404.liquid
- src/webapp/themes/bare/500.liquid
- src/webapp/themes/bare/login.liquid
- src/webapp/themes/bare/subscribe.liquid
Add error pages
Add exception filter
Fix error of the creation of the subscription trial
Add log for wrong password
Add pages 404 and 500
_Solved_
Closes #30 
WIP #8 
_Added_
- #789
Not sure of the solution
> Feat(): Add error pages for login and signup

- data/themes/fresh-sso/index.liquid
- data/themes/fresh-sso/login.liquid
- data/themes/fresh-sso/reset-password.liquid
- data/themes/fresh-sso/signup.liquid
- data/themes/fresh/login.liquid
- data/themes/fresh/reset-password.liquid
- data/themes/fresh/signup.liquid
- src/themes/fresh/src/data/error.yml
- src/themes/fresh/src/pages/index-sso.html
- src/themes/fresh/src/pages/login.html
- src/themes/fresh/src/pages/reset-password.html
- src/themes/fresh/src/pages/signup.html
- src/webapp/src/filters/http-exceptions.filter.ts
- src/webapp/src/main.app.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/src/website/controllers/public.controller.ts
- src/webapp/themes/fresh
- src/webapp/themes/fresh-sso
Add error messages to Fresh theme.
_Solved_
Partially #8, #11
> Theme/fresh: error handling

- README.md
- docs/.bundle/config
- docs/02-start/01-customize-website.md
- docs/02-start/02-try-user-flows.md
- docs/02-start/index.md
- docs/Gemfile
- docs/Gemfile.lock
Add docs to "Customize the Website"
> Docs: add "Customize the Website"

- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/api/api.module.ts
- src/webapp/src/api/controllers/v1/api.payment.controller.ts
- src/webapp/src/payments/services/payments.service.ts
- src/webapp/src/website/controllers/payments.controller.ts
- src/webapp/themes/bare/assets/stripe.js
- src/webapp/themes/bare/subscribe.liquid
Support 3ds flow.
Improves bare template to use the newly added `stripe.js` code.
Fix a few bugs.
_Solved_
#42 
_Added_
None
Heavily used stripe example code (https://github.com/stripe-samples/subscription-use-cases/)
> Stripe special cases

- src/webapp/src/accounts/entities/accountUser.entity.ts
- src/webapp/src/accounts/entities/userCredentials.entity.ts
- src/webapp/src/api/controllers/v1/api.authentication.controller.ts
- src/webapp/src/auth/local.strategy.ts
- src/webapp/src/migration/1613050217743-init3.ts
- src/webapp/src/migration/1613050217744-init4.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/test/authentication.e2e-spec.ts
- src/webapp/test/config.ts
- src/webapp/themes/bare/login.liquid
- src/webapp/themes/bare/signup.liquid
Add error messages to login and signup pages and API calls.
*NOTE* updated migrations. The DB MUST be rebuilt
_Solved_
Closes #8
None
> Login error messages

- src/webapp/src/middlewares/websiteData.middleware.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/src/website/controllers/common.controller.ts
- src/webapp/src/website/controllers/payments.controller.ts
- src/webapp/src/website/controllers/public.controller.ts
- src/webapp/src/website/utilities/render.ts
- src/webapp/src/website/website.module.ts
- src/webapp/themes/bare/reset-password.liquid
- src/webapp/themes/bare/subscribe.liquid
Add middleware
Add rendering helpoer
Use helper in controllers + refactor code
Add alerts sections in bare theme
Closes #53
None, but we need to discuss if want to have a global alerting system. Not strictly related with this PR, but since I have added alert sections in the template we need a way to handle this.
> feat: Add website middleware

- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/website/controllers/user.controller.ts
- src/webapp/themes/bare/user.liquid
feat: Add self service user list
Closes #62
> feat: Add self service user list

- src/themes/fresh/src/data/alert.yml
- src/themes/fresh/src/data/website.yml
- src/themes/fresh/src/js/main.js
- src/themes/fresh/src/pages/user.html
- src/themes/fresh/src/partials/user-billing.html
- src/themes/fresh/src/partials/user-general.html
- src/themes/fresh/src/partials/user-security.html
- src/themes/fresh/src/partials/user-team.html
- src/themes/fresh/src/sass/sass/helpers/_all.sass
- src/webapp/src/filters/http-exceptions.filter.ts
- src/webapp/src/website/controllers/public.controller.ts
- src/webapp/src/website/controllers/user.controller.ts
Add account settings page, aka /user
none
> Theme/fresh: account settings

- src/webapp/src/accounts/dto/new-user.input.ts
- src/webapp/src/accounts/services/accounts.service.spec.ts
- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/notifications/notifications.service.ts
- src/webapp/src/website/controllers/user.controller.ts
- src/webapp/themes/bare/email/invited_user.liquid
- src/webapp/themes/bare/user.liquid
Pages in the website and logic in the BE
New 'invited user' email template
Closes #63
Added #68 
API still missing (see #68)
> Self invite user

- src/themes/fresh/src/data/user.yml
- src/themes/fresh/src/data/website.yml
- src/themes/fresh/src/pages/user.html
- src/themes/fresh/src/partials/navbar-index.html
- src/themes/fresh/src/partials/navbar.html
- src/themes/fresh/src/partials/user-general.html
- src/webapp/codecov.yml
- src/webapp/src/filters/http-exceptions.filter.ts
- src/webapp/src/settings/settings.service.spec.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/website/controllers/public.controller.ts
- src/webapp/src/website/controllers/user.controller.ts
- src/webapp/src/website/utilities/render.ts
Add req.user to the rendering vars, in a centralize place.
> Centralize user in rendering variables

- codecov.yml
- src/webapp/themes/bare/index.liquid
Restore the correct indication whether the user is logged in or not
Restore the correct indication whether the email is verified or not
Closes #67
> fix: Fix display bug in bare theme index page

- src/webapp/src/accounts/entities/user.entity.ts
- src/webapp/src/accounts/services/users.service.spec.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/accounts/test/testData.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/migration/1615556774610-add-username-to-user.ts
- src/webapp/src/settings/settings.entity.ts
- src/webapp/src/settings/settings.service.spec.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/themes/bare/signup.liquid
Allow to pass additional user data at signup.
Add unique username
_Solved_
Closes #82
None
> Additional user data

- src/demo-flask/.gitignore
- src/demo-flask/README.md
- src/demo-flask/requirements.txt
- src/demo-flask/src/main.py
> feat: add the flask demo

- README.md
- docker-compose.yml
- src/webapp/.dockerignore
- src/webapp/Dockerfile
* Update the base image in order to use the current Debian "stable" (`buster`) and Node "active LTS" (`14.x`)
* Add `.dockerignore` file to exclude useless sources
* Revise the layers in order to make the resulting image as deterministic as possible
* Revise the compose file in order to build the images at runtime (if `--build` is provided)
_Solved_
- None
_Added_
- None
Some tweaks on `data/config/saasform.yml`, but purely related to my devenv.
> Revise saasform/saasform Dockerfile

- src/webapp/src/website/controllers/authentication.controller.ts
> Prevent logged users from re-login

- src/webapp/package.json
- src/webapp/src/settings/settings.service.spec.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/yarn.lock
Redirect to top level domain after logout
> Logout: redirect to top level domain

- data/themes/fresh-sso/page.liquid
- data/themes/fresh/page.liquid
- src/themes/fresh/src/pages/page.html
> Theme/fresh: various improvements

- .gitignore
- src/webapp/package.json
- src/webapp/src/accounts/services/accounts.service.spec.ts
- src/webapp/src/accounts/services/accountsUsers.service.spec.ts
- src/webapp/src/accounts/services/users.service.spec.ts
- src/webapp/src/api/controllers/v1/api.authentication.controller.ts
- src/webapp/src/app.module.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/payments/services/payments.service.spec.ts
- src/webapp/src/payments/services/payments.service.ts
- src/webapp/src/settings/settings.entity.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/validator/validation.service.spec.ts
- src/webapp/src/validator/validation.service.ts
- src/webapp/src/validator/validator.module.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/test/authentication.e2e-spec.ts
Redirects users without a valid subscription to the billing page.
It is possible to prevent the redirect by setting `subscription_optional: true` in the website settings.
_Solved_
Close #38 
_Added_
https://github.com/saasform/saasform/projects/1#card-57502416
None
> #38 redirect non paying accounts to payment page

- data/themes/bare/user.liquid
- src/webapp/src/accounts/services/users.service.spec.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/api/api.module.ts
- src/webapp/src/api/controllers/v1/api.payment.controller.ts
- src/webapp/src/api/controllers/v1/api.user.controller.ts
- src/webapp/src/website/controllers/user.controller.ts
- src/webapp/src/website/utilities/render.ts
- src/webapp/test/user.e2e-spec.ts
Update user password.
Website pages and API. Probably must be updated when the "login with google" PR arrives.
_Solved_
close #106 
_Added_
None
e2e tests fails when run together because they both expect that the db is clean, but it is only dropped once before running the tests.
> #106 update password

- data/config/saasform.yml
- src/themes/fresh/src/js/libs/auth/google.js
- src/themes/fresh/src/js/main.js
- src/themes/fresh/src/layouts/default.html
- src/webapp/package-lock.json
- src/webapp/package.json
- src/webapp/src/accounts/entities/userCredentials.entity.spec.ts
- src/webapp/src/accounts/entities/userCredentials.entity.ts
- src/webapp/src/accounts/services/userCredentials.service.spec.ts
- src/webapp/src/accounts/services/userCredentials.service.ts
- src/webapp/src/accounts/services/users.service.spec.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/accounts/test/testData.ts
- src/webapp/src/api/controllers/v1/api.authentication.controller.ts
- src/webapp/src/auth/auth.guard.ts
- src/webapp/src/auth/auth.module.ts
- src/webapp/src/auth/auth.service.spec.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/auth/google.service.ts
- src/webapp/src/migration/1616418580476-add-email-to-user-credentials-entity.ts
- src/webapp/src/migration/1616444592410-update-credential-in-user-credentials-entity.ts
- src/webapp/test/authentication.e2e-spec.ts
- src/webapp/yarn.lock
test: e2e google signin
refactor: credential and email columns
test: credential and email column
fix: email column with not null constraint
fix: credential column constraints
test: e2e db initialization
test: find user credential by email
fix: find user credential by email
feat: google oauth client
chore: package-lock updated with google-auth-library
feat: google oauth nestjs guard
fix: import
fix: test using the updated users_credentials
test: on google signin service
feat: on google signin service
test: e2e google signin
feat: google signin attached
chore: locks updated
This PR provides the google signin feat into the actual authentication flow.
It allows you to connect a Google account to an existing user with the same registered email.
Then It updates the actual `users_credentials` …
> feat: google signin

- data/config/website.yml
- data/themes/fresh-sso/404.liquid
- data/themes/fresh-sso/500.liquid
- data/themes/fresh-sso/page.liquid
- data/themes/fresh-sso/user.liquid
- data/themes/fresh/404.liquid
- data/themes/fresh/500.liquid
- data/themes/fresh/index.liquid
- data/themes/fresh/page.liquid
- data/themes/fresh/user.liquid
- src/themes/fresh/src/data/website.yml
- src/themes/fresh/src/layouts/index.html
- src/themes/fresh/src/layouts/page.html
- src/webapp/src/interceptors/csp.interceptor.ts
- src/webapp/src/main.app.ts
- src/webapp/src/settings/chatbot.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/website/website.module.ts
> Chatbot support

- src/webapp/src/payments/services/payments.service.spec.ts
Add some test. Most of the code will be refactored in #96.
_Solved_
Close #65
> test: add unit test for payment service

- data/config/website.yml
- src/webapp/src/settings/chatbot.ts
- src/webapp/src/settings/settings.service.ts
Integration with open source chatbot Chaskiq: https://chaskiq.io
https://github.com/saasform/saasform/pull/124
> Chatbot: add Chaskiq

- docker-compose.yml
> Fix missing volumes in docker-compose

- src/webapp/src/interceptors/csp.interceptor.ts
- src/webapp/src/settings/chatbot.ts
> Fix CSP blocking analytics

- src/webapp/src/api/api.module.ts
- src/webapp/src/api/controllers/v1/api.team.controller.ts
- src/webapp/test/team.e2e-spec.ts
Add API for getting user list of a team.
WIP #146, still missing the UI part
None
> #146 user/team api

- src/webapp/.gitignore
- src/webapp/package.json
- src/webapp/src/filters/http-exceptions.filter.ts
- src/webapp/src/main.app.ts
- src/webapp/src/utilities/reporting.ts
Working version of bugout crash reporting.
> Bugout reporting

- docker-compose.yml
- src/webapp/package.json
- src/webapp/src/filters/http-exceptions.filter.ts
- src/webapp/src/main.app.ts
- src/webapp/src/main.ts
- src/webapp/src/utilities/base.controller.ts
- src/webapp/src/utilities/reporting.ts
- src/webapp/yarn.lock
Reporting: minor refactor and fix linter
> Reporting: minor refactor and fix linter

- src/themes/fresh/src/data/user.yml
- src/themes/fresh/src/data/website.yml
- src/themes/fresh/src/partials/invite.html
- src/themes/fresh/src/partials/user-team.html
- src/themes/fresh/yarn.lock
- src/webapp/src/accounts/services/accountsUsers.service.spec.ts
- src/webapp/src/accounts/services/accountsUsers.service.ts
- src/webapp/src/api/controllers/v1/api.team.controller.ts
- src/webapp/test/invite-user.e2e-spec.ts
Add team page to fresh
_Solved_
#146
> 146 fresh team

- data/themes/fresh/robots.liquid
- src/webapp/src/website/controllers/public.controller.ts
Add sitemap and robots.txt to let Google index landing pages
> Add sitemap and robots.txt

- src/demo-express/views/index.jade
_Adds email verification and subscription status fields to express-demo saas_
_Solved_
- #140 (express)
_Could not find the payment status field in the JWT or req.user_
> Add fields to the demo saas 

- src/themes/fresh/src/data/item.yml
- src/themes/fresh/src/layouts/secured.html
- src/themes/fresh/src/partials/pricing.html
- src/webapp/doc/design_docs/150_billing_data.md
- src/webapp/doc/design_docs/161_change_plan.md
- src/webapp/src/accounts/services/accounts.service.spec.ts
- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/payments/services/payments.service.spec.ts
- src/webapp/src/payments/services/payments.service.ts
- src/webapp/src/website/utilities/render.ts
Allow to update the plan.
Fresh + BE + API + tests.
Closes #161 
Only uses the default payment method. See https://github.com/saasform/saasform/projects/1#card-60552159
> #161 change plan

- src/demo-flask/src/main.py
- src/demo-flask/src/templates/base.html.j2
- src/demo-flask/src/templates/index.html.j2
- _Adds templates to demo-flask_
- _Adds fields to demo saas_
- _Aligns demo-express with demo-flask_
_Solved_
- #140
- #141
> fix: fields added & aligned (#140) (#141)

- src/e2e-test/features/checkHomePage.feature
- src/e2e-test/features/checkUserProfile.feature
- src/webapp/src/website/controllers/public.controller.ts
- src/webapp/src/website/utilities/render.ts
Add e2e tests and fix corner cases
> Add e2e tests and fix corner cases

- src/webapp/src/interceptors/csp.interceptor.ts
- src/webapp/src/settings/settings.service.ts
Add unsafe option to disable CSP
> Add unsafe option to disable CSP

- src/webapp/package.json
- src/webapp/src/accounts/services/accounts.service.spec.ts
- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/api/controllers/v1/api.user.controller.ts
- src/webapp/src/main.app.ts
- src/webapp/src/payments/services/payments.service.ts
- src/webapp/src/settings/settings.entity.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/website/utilities/render.ts
- src/webapp/test/authentication.e2e-spec.ts
- src/webapp/test/change-password.e2e-spec.ts
- src/webapp/test/delete-user.e2e-spec.ts
- src/webapp/test/invite-user.e2e-spec.ts
- src/webapp/test/linked-domain.e2e-spec.ts
- src/webapp/test/team.e2e-spec.ts
- src/webapp/test/update-user.e2e-spec.ts
Add update profile API
Allow to specify in settings the length of trial. If 0 is provided, no trial is created
> Update profile api

- src/webapp/src/accounts/entities/userCredentials.entity.ts
- src/webapp/src/accounts/services/users.service.ts
- src/webapp/src/api/controllers/v1/api.authentication.controller.ts
- src/webapp/src/auth/auth.guard.ts
- src/webapp/src/auth/auth.service.spec.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/auth/azuread.strategy.ts
- src/webapp/src/auth/jwt.strategy.ts
- src/webapp/src/auth/local.strategy.ts
- src/webapp/src/interceptors/csp.interceptor.ts
- src/webapp/src/main.app.ts
- src/webapp/src/website/controllers/public.controller.ts
- src/webapp/test/authentication.e2e-spec.ts
- src/webapp/test/linked-domain.e2e-spec.ts
Complete the work started in #184 
Need to add tests and reuse these new methods for Google (and in future other socials)
> Azure: complete login/signup flow

- src/webapp/package.json
- src/webapp/yarn.lock
> Add New Dependency: TOTP

- data/config/saasform.yml
- src/themes/fresh/src/img/logo/miracl.svg
- src/themes/fresh/src/pages/index-sso.html
- src/themes/fresh/src/pages/login.html
- src/themes/fresh/src/pages/signup.html
- src/webapp/package.json
- src/webapp/src/auth/auth.guard.ts
- src/webapp/src/auth/auth.module.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/auth/miracl.strategy.ts
- src/webapp/src/settings/settings.entity.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/website/controllers/authentication.controller.ts
- src/webapp/yarn.lock
Add authentication via [Miracl](https://miracl.com).
This PR should also serve as an example on how to add a new OAuth2/OIDC provider. See the individual commits:
1. Add config options
2. Add strategy, guard and endpoints
3. Add login button in webpages
4. Add tests and documentation
> Authentication via Miracl

- data/themes/fresh-sso/payment.liquid
- data/themes/fresh/payment.liquid
- src/themes/fresh/src/pages/payment.html
- src/webapp/src/accounts/services/accounts.service.ts
- src/webapp/src/accounts/services/accountsDomains.service.ts
- src/webapp/src/api/controllers/v1/api.payment.controller.ts
- src/webapp/src/auth/auth.service.ts
- src/webapp/src/payments/services/killbill.service.ts
- src/webapp/src/payments/services/payments.service.ts
- src/webapp/src/payments/services/stripe.service.ts
- src/webapp/src/settings/settings.service.ts
- src/webapp/src/utilities/basePaymentProcessor.service.ts
Various improvements to the force payment after signup flow.
> Signup: improvements on force payment flow

- .github/pull_request_template.md
- src/demo-express/yarn.lock
- src/webapp/src/accounts/accounts.module.ts
- src/webapp/src/accounts/dto/user.dto.ts
Added Users DTO file. Also updated src/demo-express/yarn.lock file.
_Solved_
_Added_
_Ideally none_
> GraphQL: add Users DTO file

- data/themes/fresh-sso/assets/js/bundle.js
- data/themes/fresh/assets/js/bundle.js
- src/themes/fresh/src/js/libs/auth/google.js
- src/webapp/src/accounts/entities/userCredentials.entity.ts
- src/webapp/src/api/controllers/v1/api.user.controller.ts
- src/webapp/src/auth/auth.guard.ts
- src/webapp/src/auth/google.service.ts
- src/webapp/src/settings/settings.entity.ts
- src/webapp/src/settings/settings.service.ts
Feat(): Fetch and save the refresh token from google
Fix(): remove unused providers from oauth provider API
_Ideally none_
> Google refresh token

- data/config/website.yml
- src/themes/fresh/src/partials/user-security.html
- src/webapp/src/settings/settings.service.ts
> create totp html
